### ISSUE TITLE
Unable to run both Enzo and Ottobit Jr. Editors at the same time

### ISSUE THREAD

**Issue by SpaceCadet64** [ElliotGarbus/Enzo-Editor-and-Librarian#10]
Hard to say if this would be possible, but I am attempting to manage patches for both my Enzo and Ottobit Jr.
I regularly use both pedals together for further sonic options and it would be great to be able to edit both pedals at the same time.

When I have one of the editors open and connected to a pedal, attempting to open the other one prompts a fatal error. Once the first one is closed the other one can be opened successfully.

Is there any possibility of this functionality in the future?

**Comment by ElliotGarbus** [comment]
It should work now.  They need to be on separate midi channels.  I often edit multiple pedals at the same time.

**Comment by ElliotGarbus** [comment]
I just brought them both up at the same time.  Make sure you have each of them on a separate midi channel.  Make sure each pedal is connected to the MIDI I/O with a TRS cable.   If you continue to have issues let me know we can do some deeper trouble shooting.

**Comment by SpaceCadet64** [comment]
Hey Elliott,
Yes I've gone back through and double checked the global settings. The pedals are on different channels and are set to MIDI Out.
They each work with their editors separately, but I still cannot get them to work at the same time.
I've recorded the issue for you to have a look at.
https://youtu.be/088o8geIWzg

Thanks!

**Comment by ElliotGarbus** [comment]
This error means there is a failure opening the midi port.  This suggests an issue with the USB to MIDI device you are using.  What is the brand and model of your USB to MIDI interface?    This could be the issue.  

There is a log file with more details on the failure that is stored on your computer it will be located in the following directory.  C:\Users\YourUserName\.kivy\logs The log files are text files.  Look for a recent file that includes the error, and share this with me.  I'll see if there is more information to help root cause the issue..

**Comment by SpaceCadet64** [comment]
I am using a cheap no name usb to midi device. I'm sensing that that may be the issue. I can test again with my Focusrite interface after I get some midi cables for it.

In the meantime, here are the logs.
First I launched the Enzo Editor successfully and then attempted to launch the Ottobit Editor to replicate the error.

Here is the successful Enzo log:
[Enzo Successful Launch Log.txt](https://github.com/ElliotGarbus/Enzo-Editor-and-Librarian/files/7739364/Enzo.Successful.Launch.Log.txt)

And here is the subsequent, failed Ottobit log:
[Ottobit Unsuccessful Launch Log.txt](https://github.com/ElliotGarbus/Enzo-Editor-and-Librarian/files/7739366/Ottobit.Unsuccessful.Launch.Log.txt)

Thanks

**Comment by SpaceCadet64** [comment]
It seems that this usb to midi adapter does not support being used by multiple programs at the same time.
I used Ableton to send a MIDI clock signal to the Enzo and was unable to launch either of the editors while the clock signal was being sent.

So for now I guess the issue has been solved. I'll test with the Focusrite interface and follow up if there are any further issues.

Cheers
