### ISSUE TITLE
Midi Preset Control and Expression at the same time...

### ISSUE THREAD

**Issue by mayasfinest** [ElliotGarbus/Enzo-Editor-and-Librarian#3]
Hi Elliot,
i hope you can help me out here.
I see you also implented Meris expression pedals feature in your editors.
How is it possible to have an expression pedal connected to your editor/Meris input when there is no spare input for it?

My setup is:
Laptop (with your editor) going through a Roland UM-One Midi interface to the Meris I/O and then into the pedal.

What extra device do i need to have? What do i have to configure and how...?

Send the Expression pedal firstly though a Midi Keyboard with USBout connected to my laptop? And then connect this keyboard somehow to your editor..? Most keyboards will not have CC-programmable outputs... i am confused.

Best,
Jörg

**Comment by mayasfinest** [comment]
Hi Elliot,
i don't know, if this is the "official way" to get in contact with you. 
As my post above is not really an issue with your editor but rather i am looking for help or an explanation for a certain setup with expressionpedal and your editor.

Thanks for dropping me a line,
stay healthy
Jörg

**Comment by ElliotGarbus** [comment]
@mayasfinest 
Jorg,
Apologies for the delay.  I did not have notifications turned on for this repository.  I've fixed that now.

**Your question**: If a Roland UM-One is connected directly to the Meris MIDI I/O how can expression pedal be used at when the expression input is being used for MIDI?

**Answer:**  You need to use a MIDI expression pedal.  You can use a USB based device or a 5-pin MIDI based device.  
I for example have a KMI Softstep.  The Softstep can connect directly to USB, I connect an expression pedal to the Softstep, send the CC messages to the Roland UM-One on the channel that the Enzo is using.  
Similarly it looks like you could connect a MorningStar MC-series devices to send midi expression over usb.
It looks like you could also do something like this with many of the Disaster Area Controllers.
A simple usb based device that looks like it should work is the audiofront midi expression to usb:  https://www.audiofront.net/MIDIExpression.php

Another alternative would be to have a device that provides an expression pedal to midi conversion, and midi-in and midi-out/thru - I believe many of the disaster area products can do this - but you should confirm with DisasterArea.  In this case you would connect a ring with multiple 5-pin devices.   
[UM-One out] ->[midi-in 5 pin device with exp in and out/thru] -> [Meris MIDI I/O in -> Meris MIDI I/O Out] -> [UM-One In]

I hope that made sense.   Happy to answer any follow up questions.

**Comment by mayasfinest** [comment]
Hi Eliott,
thanks for your helpful answer. 
Now i got myself a 4 port midiexpression from audiofront (the big one). It recognizes my expression pedal and seems to send out expression data ( converted to CC#4 as meris wants it) via USB to the UM-one  and to my Meris Midi I/O and Enzo which is on channel 3. 
Unfortunately it doesn't get it's data through to the Enzo. 
As I only have one USB port in tablet i have to go through a hub, both devices work and have enough power.
I assume, that the Audiofront device (which is programmed via a nifty editor) is not passing its data to the USB, but it's all set there, the right channel and the right CC-conversion...
I have no idea where to begin... maybe it's dead simple...
Do i have to change anything in your editor in the input section or just leave both to the UM-One? 
Shall I try the DIN5pin way? But i don't really understand the routing way and what you wrote above does not make a difference (or i don't understand it ;-) )

Any ideas, what to try...?

PS: Correct me if i am wrong. The way to program the two values in your editor is: 
1. Hit the "Prgm Exp Pedal" button
2. Set values for "Toe up"
3. Switch to "Toe down"
4. Set values for "Toe down"
5. Turn off "Prgm Exp Pedal"

Best,
Jörg

**Comment by ElliotGarbus** [comment]
Jorg,
I don't really know why your expression is not working.  Here are a few things to try.
Set your expression pedal to control the pitch on the Enzo (this way you can easily hear if it is working).  Pitch is CC#16.
The factory presets all have rather dramatic pedal effects already - so any of the factory presets should also work.
Double check that the range of the pedal is from 0 to 127.  Also make sure you are using an expression pedal - not a volume pedal.

You could install a midi monitor on your computer to see if the data is being sent correctly.  Here is a free midi monitor that i like to use: https://www.bome.com/products/sendsx

Your description for setting the Toe-Up and Toe-Down settings in the editor is correct.  You can repeatedly press the Toe-Up/Toe-Down toggle button to see each setting.

Double check the routing on the audiofront device, that it is sending to USB.  I notice in the docs if the AudioFront is powered by a seperate power supply it ignores the routing data.

You should be able to get this all working with USB.  Get the midi monitor to see what is going on.  Feel free to reach out and show me what is on the monitor if you can't figure it out.   Good Luck!

**Comment by mayasfinest** [comment]
Me again... still no luck :-(

I tried recording the (expression) pedals data in Nuendo, everything works as expected, the channel, the CC, the range, everything is recorded correctly; i can change it on-the-fly and it changes ttoo - so it seems to send out midi over usb.

But the UM-One doesn't seem to pick it up correctly or at all, although i have no issues with your editor's in/out - turning knobs on the meris changes the editor and vice versa (not physically ;-)

Is there anything i am missing in the meris pedals options? I have to use CC#4 to have expression pedal functioning, right?
And i have to set Meris Expression Mode to "MIDI" not to "EXP", right? And Midi "THRU" on the Meris has to be set to "MIDI OUT"

Any further ideas...?

Best,
Jörg

**Comment by ElliotGarbus** [comment]
You have the pedal configured correctly.

You can ask AudioFront about the usb config.  I'm hopeful it will work with the 5-pin din.  Connect as follows:
UM-One OUT (labeled "to MIDI IN") to the MIDI In on the AudioFront Device;
Midi Out of the AudioFront Device to the MIDI In on the Meris MIDI I/O;
Midi Out of the Meris MIDI IO to the MIDI in on the UM-One (Labeled "to MIDI OUT").

I would start by adjusting the routing to the 5-pin midi on the AudioFront device.  If that does not work try using it in standalone mode.  

Just had another idea... Is there a way to forward the expression content in your DAW?  You DAW is receiving the content, can it send the received expression signal out to the Enzo?

**Comment by mayasfinest** [comment]
Ahhh, this extra DIN5-round did the trick :-)

But i have to also use the USB connection, otherwise i couldn't use your editor. The value changes are not transmitted via the DIN-line only.
Is there a way to reflect the transition of values in the editor? I mean moving knobs when pressing the pedal?
For now i can only see the different states of toe-up and toe-down when pressing the button, then the values change (which is totally fine).

Wow, the Expression pedal possibility in conjuction with your bi-directional editor opens up a whole new level, stunning...
If i only had 4 feet ;-)

Thanks so far,
stay healthy
Jörg

**Comment by ElliotGarbus** [comment]
I think you would need to setup the expression pedal device in standalone mode and power it from a different power connection.  Then it should work without the USB connected to the PC.

The editor does not dynamically reflect the changes of the expression pedal.  This was just a design decision to simplify things.  The pedal processes the expression signal directly - anything I put on the screen would be an interpretation of the pedal settings.  
Enjoy and Stay Healthy!
-Elliot
